#!/usr/bin/python3

import time
import sys
import math

def factor(n):
    if n == 0:
        print ("0=0*0")
        return
    if n == 1:
        print ("1=1*1")
        return
    a = int(math.sqrt(n))
    #a = n//2
    if n % 2 == 0:
        print("{:d}={:d}*2".format(n, n//2))
        return
    for i in range(a + 1, 3, 2):
        if n % i ==  0:
            p = i
            q = n // p
            print("{:d}={:d}*{:d}".format(n, q, p))
            return
    print("{:d}={:d}*1".format(n, n))

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename, 'r') as file:
        lines = file.readlines()
except IOError:
    sys.exit(1)


for line in lines:
    n = int(line.strip())
    factorisation = factor(n)
