#!/usr/bin/python3

import time

def factor(n):
    if n == 1:
        return
    a = n // 2
    for i in range(2, a + 1):
        if n % i ==  0:
            p = i
            q = n // p
            print("{:d}={:d}*{:d}".format(n, p, q))
            return
    print("{:d}=1*{:d}".format(n, n))

