#!/usr/bin/python3

import sys 
import math

def is_prime(n):
    if n <= 1:
        return False
    if n % 2 == 0 or n % 3 == 0:
        return False
    range_end = int(math.sqrt(n)) + 1
    for i in range(2, range_end):
        if n % i == 0:
            return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6

    return True

def prime_factors(n):
    range_end = int(math.sqrt(n))
    for i in range(2, range_end+1):
        if n % i == 0:
            j = n // i
            if is_prime(i) and is_prime(j):
                print("{:d}={:d}*{:d}".format(n, j, i))
                return
    print("{:d}={:d}*{:d}".format(n, n, 1))

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename, 'r') as file:
        n = int(file.readline().strip())
except IOError:
    sys.exit(1)

prime_factors(n)
